title: "SecNotes"
description: "Documentación de labs, explicadas de forma sencilla para ayudar a entender técnicas reales de hacking ético."
permalink: "/:title/"
baseurl: "/secnotes"
url: "" # el dominio base, por ejemplo: "https://yorve.github.io"

# Author Settings
author: "Yorve CSEC"
author-img: "logo.png"
about-author: "Aqui encontrarás writeups formativos sobre hacking ético, pensados especialmente para quienes están comenzando."
social-github: "yorve"
social-linkedin: "yonathan-rivera-velozo-9b362798"
social-email: "yorve.csec@gmail.com"

# Disqus
discus-identifier: "Yorve"

# Tracker
analytics: "G-G8V2DW9MZ5"

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude:
  - "node_modules"
  - "gulpfile.js"
  - "package.json"
  - "yarn.lock"
